header:
  license:
    spdx-id: MIT
    copyright-owner: ChanMeng666
    # 移除固定年份，使用自动检测
    # copyright-year: '2024' 
    
  paths:
    - '*.js'        # 添加这行来包含根目录的 JS 文件
    - 'src/**/*.js' # 保留对 src 目录的检查
    
  paths-ignore:
    - 'node_modules/**'
    - 'dist/**'
    - 'build/**'
    - '**/*.json'
    - '**/*.md'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/*.svg'
    - 'LICENSE'
    
  comment: on-failure

  language:
    JavaScript:
      extensions:
        - ".js"
      comment_style_id: SlashAsterisk

dependency:
  files:
    - package.json
