header:
  license:
    spdx-id: MIT
    copyright-owner: ChanMeng666
    copyright-year: '2025'
    
  paths:
    - '**/*.js'    # 只检查 JavaScript 文件
    
  paths-ignore:
    - 'node_modules/**'
    - 'dist/**'
    - 'build/**'
    - '**/*.json'
    - '**/*.md'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/*.svg'
    - 'LICENSE'
    
  comment: on-failure

dependency:
  files:
    - package.json
