name: License Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  fix-license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Fix License Header
      uses: apache/skywalking-eyes/header@main
      with:
        mode: fix
        token: ${{ secrets.GITHUB_TOKEN }}
        config: .licenserc.yaml
        
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: License Bot
        author_email: license_bot@github.com
        message: 'chore: add missing license headers'
