name: License Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  fix-license:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Fix License Header
      uses: apache/skywalking-eyes/header@main
      with:
        mode: fix
        token: ${{ secrets.GITHUB_TOKEN }}
        config: .licenserc.yaml
        
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: add missing license headers'
        file_pattern: '**/*'
