name: Update License Year

on:
  schedule:
    - cron: '0 0 1 1 *'  # Run every January 1st
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: write

jobs:
  update-license:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get current year
      # Get current year
      id: date
      run: echo "::set-output name=year::$(date +'%Y')"
    
    - name: Update LICENSE year
      # Update year in LICENSE file
      run: |
        if [ -f LICENSE ]; then
          # Replace year pattern in LICENSE file
          sed -i "s/Copyright (c) [0-9]\{4\}/Copyright (c) ${{ steps.date.outputs.year }}/g" LICENSE
        fi
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add LICENSE
        git diff --staged --quiet || git commit -m "Update LICENSE year to ${{ steps.date.outputs.year }}"
        git push
